DROP TRIGGER IF EXISTS subscribers_set_updated_at ON subscribers;
DROP TRIGGER IF EXISTS site_settings_set_updated_at ON site_settings;
DROP TRIGGER IF EXISTS admin_notifications_set_updated_at ON admin_notifications;
DROP TRIGGER IF EXISTS friend_links_set_updated_at ON friend_links;
DROP TRIGGER IF EXISTS dynamics_set_updated_at ON dynamics;
DROP TRIGGER IF EXISTS articles_set_updated_at ON articles;
DROP TRIGGER IF EXISTS series_set_updated_at ON series;
DROP TRIGGER IF EXISTS categories_set_updated_at ON categories;
DROP TRIGGER IF EXISTS admin_accounts_set_updated_at ON admin_accounts;

DROP TABLE IF EXISTS email_deliveries;
DROP TABLE IF EXISTS subscribers;
DROP TABLE IF EXISTS site_settings;
DROP TABLE IF EXISTS admin_notifications;
DROP TABLE IF EXISTS friend_links;
DROP TRIGGER IF EXISTS article_likes_update_count ON article_likes;
DROP FUNCTION IF EXISTS yukilog_update_article_like_count();
DROP TABLE IF EXISTS article_likes;
DROP TRIGGER IF EXISTS dynamic_likes_update_count ON dynamic_likes;
DROP FUNCTION IF EXISTS yukilog_update_dynamic_like_count();
DROP TABLE IF EXISTS dynamic_likes;
DROP TRIGGER IF EXISTS dynamics_create_metrics ON dynamics;
DROP FUNCTION IF EXISTS yukilog_create_dynamic_metrics();
DROP TABLE IF EXISTS dynamic_metrics;
DROP TRIGGER IF EXISTS articles_create_metrics ON articles;
DROP FUNCTION IF EXISTS yukilog_create_article_metrics();
DROP TABLE IF EXISTS article_metrics;
DROP TRIGGER IF EXISTS comments_validate_parent ON comments;
DROP FUNCTION IF EXISTS yukilog_validate_comment_parent();
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS dynamic_media;
DROP TABLE IF EXISTS dynamics;
DROP TABLE IF EXISTS article_tags;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS media_assets;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS admin_sessions;
DROP TABLE IF EXISTS admin_accounts;
DROP FUNCTION IF EXISTS yukilog_set_updated_at();
